DROP DATABASE IF EXISTS matrix_spring;
DROP USER IF EXISTS `mrfoot`@`%`;
DROP USER IF EXISTS `vermillion`@`%`;
CREATE DATABASE IF NOT EXISTS matrix_spring CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS `mrfoot`@`%` IDENTIFIED WITH mysql_native_password BY 'matrixstaff';
CREATE USER IF NOT EXISTS `vermillion`@`%` IDENTIFIED WITH mysql_native_password BY 'matrixstaff';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, REFERENCES, INDEX, ALTER, EXECUTE, CREATE VIEW, SHOW VIEW,
CREATE ROUTINE, ALTER ROUTINE, EVENT, TRIGGER ON `matrix_spring`.* TO `mrfoot`@`%`;
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, REFERENCES, INDEX, ALTER, EXECUTE, CREATE VIEW, SHOW VIEW,
CREATE ROUTINE, ALTER ROUTINE, EVENT, TRIGGER ON `matrix_spring`.* TO `vermillion`@`%`;